In [1]:
import torch


In [2]:
x_data=[1,2,3,4]
y_data=[1,4,9,16]


In [3]:
m=torch.Tensor([1.0])
c=torch.Tensor([1.0])
m.requires_grad=True
c.requires_grad=True




In [4]:
def forward(x):
    return (x*m)+c

In [5]:
def loss(x,y):
    y_hat=forward(x)
    return (y_hat-y) *(y_hat-y)
    

In [6]:
for epoch in range(100):
    k=0
    for i,j in zip(x_data,y_data):
        k+=1
        l=loss(i,j)
        l.backward()
        #print("Gradient of m and c after epoch {} and data iteration {} is : {} and {}".format(epoch,k,m.grad.data,c.grad.data))
        m.data=m-0.09*m.grad.data
        c.data=c-0.09*c.grad.data
        m.grad.data.zero_()
        c.grad.data.zero_()
    print(m*7+c)
    
    

tensor([ 28.6133])
tensor([ 31.9188])
tensor([ 33.2173])
tensor([ 34.2330])
tensor([ 35.1630])
tensor([ 36.0330])
tensor([ 36.8488])
tensor([ 37.6142])
tensor([ 38.3323])
tensor([ 39.0059])
tensor([ 39.6379])
tensor([ 40.2309])
tensor([ 40.7871])
tensor([ 41.3090])
tensor([ 41.7985])
tensor([ 42.2579])
tensor([ 42.6888])
tensor([ 43.0930])
tensor([ 43.4723])
tensor([ 43.8281])
tensor([ 44.1619])
tensor([ 44.4751])
tensor([ 44.7689])
tensor([ 45.0445])
tensor([ 45.3031])
tensor([ 45.5457])
tensor([ 45.7733])
tensor([ 45.9868])
tensor([ 46.1871])
tensor([ 46.3750])
tensor([ 46.5514])
tensor([ 46.7168])
tensor([ 46.8719])
tensor([ 47.0175])
tensor([ 47.1541])
tensor([ 47.2822])
tensor([ 47.4025])
tensor([ 47.5152])
tensor([ 47.6210])
tensor([ 47.7203])
tensor([ 47.8134])
tensor([ 47.9008])
tensor([ 47.9827])
tensor([ 48.0596])
tensor([ 48.1318])
tensor([ 48.1994])
tensor([ 48.2629])
tensor([ 48.3225])
tensor([ 48.3784])
tensor([ 48.4308])
tensor([ 48.4800])
tensor([ 48.5261])
tensor([ 48.