In [84]:
import torch
import torch.nn as nn
from torch import autograd
torch.set_default_tensor_type('torch.FloatTensor')

In [85]:
#to initialize rnn

basic_cell=nn.RNN(input_size=4,hidden_size=2,batch_first=True)
gru_cell=nn.GRU(input_size=4,hidden_size=2,batch_first=True)
lstm_cell=nn.LSTM(input_size=4,hidden_size=2,batch_first=True)

In [86]:
#inputs= (batch_size,seq_length,input_size) with batch_first=True
#hidden=(num_layers,batch_size,hidden_size)
#out,hidden=basic_cell(inputs,hidden)

In [87]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder as OHE
import numpy as np
import pandas as pd
clf=LabelEncoder()
res=clf.fit_transform(['h','e','l','l','o'])
clf=OHE()
res=res.reshape(-1,1)
final_res=clf.fit_transform(res).toarray()
res2=pd.get_dummies(['h','e','l','l','o'])
final_res


array([[0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [119]:
clf=LabelEncoder()
res=clf.fit_transform(['p','y','t','o','o'])
clf=OHE()
res=res.reshape(-1,1)
final_res_2=clf.fit_transform(res).toarray()
final_res_2

array([[0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.]])

In [118]:
inputs=autograd.Variable(torch.tensor([[final_res[0]]])).float()
inputs.size()

torch.Size([1, 1, 4])

In [93]:
#How to initialize the hidden state
#(num_layers*num_directions,batch_size,hidden_size)

In [94]:
hidden=autograd.Variable(torch.randn(1,1,2))


In [95]:
out,hiddens=basic_cell(inputs,hidden)

In [100]:
#To pass multiple sequences at same time
inputs=autograd.Variable(torch.tensor([final_res])).float()
inputs.size()

torch.Size([1, 5, 4])

In [101]:
hidden=autograd.Variable(torch.randn(1,1,2))

In [102]:
out,hiddens=basic_cell(inputs,hidden)

In [104]:
hiddens

tensor([[[ 0.1379,  0.0754]]])

In [127]:
# to use batch_size as well in rnn
inputs=autograd.Variable(torch.tensor([final_res,final_res_2])).float()#inputs= (batch_size,seq_length,input_size) with batch_first=True
hidden=autograd.Variable(torch.randn(1,2,2)) ##hidden=(num_layers,batch_size,hidden_size)
out,hiddens=basic_cell(inputs,hidden)



tensor([[[-0.5246,  0.8300],
         [-0.5455,  0.2882],
         [-0.2801, -0.3252],
         [-0.4187,  0.0914],
         [ 0.1563,  0.0322]],

        [[-0.3019,  0.9758],
         [ 0.3931, -0.2948],
         [-0.3779,  0.4290],
         [-0.6150,  0.5095],
         [-0.6095,  0.3724]]])